#ifndef FFMPEG_ERROR_H
#define FFMPEG_ERROR_H

// 错误码
typedef enum
{
    FFMPEG_OK                       = 0x0000,
    FILE_OPEN_FAILED                = 0x0001,
    MALLOC_FAILED,
    AVFORMAT_ALLOC_CONTEXT_FAILED,
    AVFORMAT_OPEN_INPUT_FAILED,
    AVFORMAT_FIND_STREAM_INFO_FAILED,
    AVFORMAT_NO_VIDEO_STREAM,
    AVCODEC_NOT_MATCH,
    AVCODEC_OPEN_FAILED,
}FFMPEG_ERROR;

#endif // FFMPEG_ERROR_H
